package com.corejsf;

import java.io.Serializable;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

@Named
@ApplicationScoped
public class AutoComplete implements Serializable {

    public String[] getLocations() {
        return new String[]{
            "Abari", "Absurdsvanj", "Adjikistan", "Afromacoland",
            "Agrabah", "Agaria", "Aijina", "Ajir", "Al-Alemand",
            "Al Amarja", "Alaine", "Albenistan", "Aldestan",
            "Al Hari", "Alpine Emirates", "Altruria",
            "Allied States of America", "BabaKiueria", "Babalstan",
            "Babar's Kingdom", "Backhairistan", "Bacteria",
            "Bahar", "Bahavia", "Bahkan", "Bakaslavia",
            "Balamkadar", "Baki", "Balinderry", "Balochistan",
            "Baltish", "Baltonia", "Bataniland, Republic of",
            "Bayview", "Banania, Republica de", "Bandrika",
            "Bangalia", "Bangstoff", "Bapetikosweti", "Baracq",
            "Baraza", "Barataria", "Barclay Islands",
            "Barringtonia", "Bay View", "Basenji", "Bahrain",
            "Bangladesh", "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia&Herzegovina",
            "Botswana",
            "Brazil",
            "BruneiDarussalam",
            "Bulgaria",
            "BurkinaFaso",
            "Myanmar/Burma",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "CapeVerde",
            "CaymanIslands",
            "CentralAfricanRepublic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "CostaRica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "CzechRepublic",
            "DemocraticRepublicoftheCongo",
            "Denmark",
            "Djibouti",
            "DominicanRepublic",
            "Dominica",
            "Ecuador",
            "Egypt",
            "ElSalvador",
            "EquatorialGuinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "FrenchGuiana",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "GreatBritain",
            "Greece",
            "Grenada",
            "Guadeloupe",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "IsraelandtheOccupiedTerritories",
            "Italy",
            "IvoryCoast(Coted'Ivoire)",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kosovo",
            "Kuwait",
            "KyrgyzRepublic(Kyrgyzstan)",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "RepublicofMacedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Moldova,Republicof",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nepal",
            "Netherlands",
            "NewZealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Korea,DemocraticRepublicof(NorthKorea)",
            "Norway",
            "Oman",
            "PacificIslands",
            "Pakistan",
            "Panama",
            "PapuaNewGuinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "PuertoRico",
            "Qatar",
            "Reunion",
            "Romania",
            "RussianFederation",
            "Rwanda",
            "SaintKittsandNevis",
            "SaintLucia",
            "SaintVincent's&Grenadines",
            "Samoa",
            "SaoTomeandPrincipe",
            "SaudiArabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "SierraLeone",
            "Singapore",
            "SlovakRepublic(Slovakia)",
            "Slovenia",
            "SolomonIslands",
            "Somalia",
            "SouthAfrica",
            "Korea,Republicof(SouthKorea)",
            "SouthSudan",
            "Spain",
            "SriLanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "TimorLeste",
            "Togo",
            "Trinidad&Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks&CaicosIslands",
            "Uganda",
            "Ukraine",
            "UnitedArabEmirates",
            "UnitedStatesofAmerica(USA)",
            "Uruguay",
            "Uzbekistan",
            "Venezuela",
            "Vietnam",
            "VirginIslands(UK)",
            "VirginIslands(US)",
            "Yemen",
            "Zambia",
            "Zimbabwe",};
    }
}
